name: Deploy Angular to GitHub Pages

# ה־workflow יפעל על כל push לענף main
on:
  push:
    branches:
      - main

# הרשאות כדי שה־workflow יוכל לשנות את התוכן ב־GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # שלב 1: שליפת הקוד מה־repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # שלב 2: התקנת Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # שלב 3: התקנת התלויות של הפרויקט
      - name: Install dependencies
        run: npm install

      # שלב 4: בניית Angular ל־production עם base-href מותאם ל־GitHub Pages
      - name: Build Angular
        run: npm run build -- --base-href="/PisgatHafakot/"

      # שלב 5: פריסה ל־GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/pisgat-hafakot